services:
  server:
    image: floor777/sterilization-directory-server:v1
    ports:
      - 3000:3000
    environment:
      - DATABASE_NAME='$DATABASE_HOSTNAME'
      - DATABASE_USERNAME='$DATABASE_USERNAME'
      - DATABASE_PASSWORD='$DATABASE_PASSWORD'
      - DATABASE_HOSTNAME='$DATABASE_HOSTNAME'

  client:
    image: floor777/sterilization-directory-client:v1
    ports:
      - 5137:5137