version: 2.1
executors:
  docker-publisher:
    environment:
      CLIENT_IMAGE_NAME: floor777/sterilization-directory-client
      SERVER_IMAGE_NAME: floor777/sterilization-directory-server
    docker:
      - image: cimg/base:2021.04
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build images of services declared in docker-compose.yml
          command: |
            cd server && docker build -t $SERVER_IMAGE_NAME:test . && cd .. && cd client && docker build -t $CLIENT_IMAGE_NAME:test .
      - run:
          name: Check docker images
          command: |
            docker images


  publish-latest:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $CLIENT_IMAGE_NAME
            docker push $SERVER_IMAGE_NAME
workflows:
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: testing
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: testing
