jobs:
  build:
    docker:
      - image: cimg/node:16.10
        auth:
          username: floor777
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            pwd && cd server && ls
      - run:
          name: LS the server folder
          command: |
            ls


            
          