jobs:
  build:
    docker:
      - image: cimg/node:16.10
        auth:
          username: floor777
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies in server and client
          command: |
            cd server && npm ci && cd .. && cd client && npm ci
      - run:
          name: LS the server folder
          command: |
            ls && cd server && ls && npm ls && npm run test


            
          