jobs:
  build:
    docker:
      - image: cimg/node:16.10
        auth:
          username: floor777
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test 