version: 2.1
executors:
  docker-publisher:
    environment:
      CLIENT_IMAGE_NAME: floor777/sterilization-directory-client
      SERVER_IMAGE_NAME: floor777/sterilization-directory-server
    docker:
      - image: cimg/base:2021.04
jobs:
  build-and-test:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build images of services declared in docker-compose.yml
          command: |
            cd server && docker build -t $SERVER_IMAGE_NAME:test . && cd .. && cd client && docker build -t $CLIENT_IMAGE_NAME:test .
      - run:
          name: Run tests on server image
          command: |
            cd server && docker run $SERVER_IMAGE_NAME:test npm run test
      - run:
          name: Run tests on client image
          command: |
            cd client && docker run $CLIENT_IMAGE_NAME:test npm run test
      - run:
          name: Check docker images
          command: |
            docker images
      - run:
          name: Archive docker images
          command: |
            docker save -o server-image.tar $SERVER_IMAGE_NAME
            docker save -o client-image.tar $CLIENT_IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./server-image.tar
            - ./client-image.tar

  test:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Print to console
          command: echo test job



  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: |
            docker load -i /tmp/workspace/client-image.tar
            docker load -i /tmp/workspace/server-image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker images
            # docker push $CLIENT_IMAGE_NAME:test
            # docker push $SERVER_IMAGE_NAME:test
workflows:
  build-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: testing
      # - test:
      #     requires: 
      #       - build
      #     filters:
      #       branches:
      #         only: testing
      - publish-latest:
          requires:
            - build-and-test

          filters:
            branches:
              only: testing
