jobs:
  build:
    docker:
      - image: cimg/node:16.10
        auth:
          username: floor777
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm ls && pwd