version: 2.1
executors:
  docker-publisher:
    environment:
      CLIENT_IMAGE_NAME: floor777/sterilization-directory-client
      SERVER_IMAGE_NAME: floor777/sterilization-directory-server
    docker:
      - image: cimg/base:2021.04
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build images of services declared in docker-compose.yml
          command: |
            docker-compose build
      # - run:
      #     name: Archive Docker image
      #     command: docker save -o client-image.tar $CLIENT_IMAGE_NAME && docker save -o server-image.tar $SERVER_IMAGE_NAME
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      # - attach_workspace:
      #     at: /tmp/workspace
      - setup_remote_docker
      # - run:
      #     name: Load archived Docker image
      #     command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $CLIENT_IMAGE_NAME:test
            docker push $SERVER_IMAGE_NAME:test
workflows:
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
