jobs:
  build:
    docker:
      - image: cimg/node:16.10
        auth:
          username: floor777
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            docker-compose up -d &&
            cd server && npm run test


            
          